# All the logs to transferred from another directory during app run.
# Below is the mentioned path
file_transfer:
  dest: 'files/json_reports'


# Execution mode: options are 1. local 2. AWS
exec_mode: 'local'

# MySQL credentials (Confidential file)
local_database:
  host: 'localhost'
  port: '3306'
  user: 'ranadeep'
  password: 'rana#123'
  db: 'profiles'

# AWS-RDS credentials (Confidential file)
database:
  host: 'vnou-solutions.cj2amuwswmdg.ap-south-1.rds.amazonaws.com'
  port: '3306'
  user: 'ranadeep'
  password: 'rana#123'
  db: 'profiles'
